# -*- coding: utf-8 -*-
"""Market_Basket_Analysis_Using_Apriori.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHd-YZcJsMRbPv9e0I5EGjy28lzP3Is8

MARKET SASKET ANALYSIS USING APRIORI

Step-1 install Libarraies
"""

# !pip install mlxtend gradio -q

"""Step-2 : import Libraries"""

import numpy as np
import pandas as pd
import gradio as gr

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

"""**Step-3 : Create Sample Transaction Data**"""

#Each list represents one customer's shopping basket
sample_transactions = [
    ["Milk", "Bread", "Butter"],
    ["Bread", "Butter"],
    ["Milk", "Bread"],
    ["Milk", "Bread", "Butter", 'Eggs'],
    ["Bread", "Eggs"],
    ["Mike", "Eggs"],
    ["Mile", "Bread", "Butter"],
    ["Bread", "Butter", "Eggs"],
    ["Mile", "Bread", "Eggs"],
    ["Mike", "Butter"]
]

"""**Step-4 : Convert Transactions to DataFrame**"""

def create_dataframe(transactions):

  #Create a TaransactionEncoder
  encoder = TransactionEncoder()

  #Convert transactions into True/False values.
  encoded = encoder.fit(transactions).transform(transactions)

  #Craete a pandas dataframe
  dataframe = pd.DataFrame(
      encoded,
      columns = encoder.columns_
  )

  return dataframe

#Create the default dataset
df = create_dataframe(sample_transactions)

"""**Step-5 : Format Association Rules**"""

def format_rules(rules):
  results = []

  #Fo through every rules
  for _, row in rules.iterrows():

    #Convert product into text
    antecedent = ",".join(row("antecedents"))
    consequent = ",".join(row("consequents"))

    #Create one rwo result
    results.append({
        "If Costomer Buys" : antecedent,
        "Then Customer May Buy" : consequent,
        "Support" : round(row["support"], 3),
        "Confidence" : round(row["confidence"], 3),
        "Lift" : round(row["lift"], 3)
    })

    #Crate results to a DataFrame
    create_dataframe(results)

"""**Step-6 : Upload CSV Dataset**"""

def upload_dataset(file):
  global df

  #if the user does not upload a file, use the default sample dataset
  if file is None:

    return("No File upload, using sample dataset", df)

  try:

    #Read the uploaded CSV file.
    uploaded_data = pd.read_csv(file)

    #Create an empty list for transactions
    transactions = []

    for _, row in upload_dataset.iterrows():
      #Create a list of products in this transactions
      items = []

      for item in row:
        #Ignore empty cells.
        if pd.notna(item):
          item = str(item).strip()
          if item != "":
            items.append(item)

    #Add the transactions if it contains products
    if len(items) > 0:
      transactions.append(items)

    #Check the dataset contains transactions
    if len(items) == 0:
      return("The uplaod dataset is empty.", pd.DataFrame())


    #Convert Transactions to DataFrame
    df = create_dataframe(transactions)

    return (f"Dataset uploaded successfully"
            f"{len(transactions)} tarnsactions found", df)

  except Exception as error:
    return(
        f"Error reading dataset : {error}", pd.DataFrame()
    )